site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://mkdocstrings.github.io/"
repo_url: "https://github.com/mkdocstrings/mkdocstrings"
edit_uri: "blob/master/docs/"
repo_name: "mkdocstrings/mkdocstrings"

theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: purple

extra_css:
- css/style.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_credits.py
    - docs/gen_doc_stubs.py
- literate-nav:
    nav_file: sidebar.md
- section-index
- coverage:
    html_report_dir: build/coverage
- mkdocstrings:
    handlers:
      python:
        setup_commands:
        - import sys
        - sys.path.append("docs")
        selection:
          new_path_syntax: yes
    watch:
    - src/mkdocstrings
